### ISSUE TITLE
exclude resources by specific tags

### ISSUE THREAD

**Issue by onlyillusion** [ekristen/azure-nuke#17]
If it possible to exclude for example resource group by specific tag?
Thank you!

**Comment by ekristen** [comment]
Not at this time, but I think it could be useful, there are some potential problems if some resources don't support tagging, but I don't think that's enough to prevent looking into adding it. Next time I'm doing some updates, I'll see what it takes.

**Comment by ekristen** [comment]
@onlyillusion tags have been added to many resources including ResourceGroup which now has [documentation](https://ekristen.github.io/azure-nuke/resources/resource-group/)
