### ISSUE TITLE
Exclude resources owned by resource group

### ISSUE THREAD

**Issue by fergoid** [ekristen/azure-nuke#31]
At the moment resource group exclusions will prevent the group being destroyed but owned resources are still flagged for destruction.  Could we add an option to also exclude the resources owned by the group?
Something like:
Filters:
  ResourceGroup:
      - foo
      - bar
  ResourceGroupAll:
    - foofoo
    - barbar

so current the exclusions filter method  is unaffected by the change .

**Comment by ekristen** [comment]
I'm not sure I follow the request, it seems you want to exclude resources by membership to a resource group? If that's the ask, shouldn't just excluding the resource group itself (which is already supported) not solve this?

**Comment by fergoid** [comment]
I'd be happy to try implementing it if you are okay with that?

**Comment by ekristen** [comment]
Pull Requests are welcome, might require back and forth. Are you asking about implementing Global Filters?

**Comment by ekristen** [comment]
This tool is being completely rewritten to use my new [libnuke](https://github.com/ekristen/libnuke) library. I've got an open issue over there to figure out how to best implement global filters. https://github.com/ekristen/libnuke/issues/25
