### ISSUE TITLE
Brew install causes issues with cleanup

### ISSUE THREAD

**Issue by Chan9390** [ekristen/azure-nuke#77]
I installed azure-nuke using the brew command: `brew install ekristen/tap/azure-nuke@1`

While the installation worked fine, executing `brew update` or `brew cleanup` always caused the following error message:

```
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:315:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:249:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:569:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:569:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:793:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:1009:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:1053:in `from_rack'
/opt/homebrew/Library/Homebrew/cleanup.rb:129:in `stale_formula?'
/opt/homebrew/Library/Homebrew/cleanup.rb:66:in `stale?'
/opt/homebrew/Library/Homebrew/cleanup.rb:450:in `block in cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:432:in `each'
/opt/homebrew/Library/Homebrew/cleanup.rb:432:in `cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:296:in `clean!'
/opt/homebrew/Library/Homebrew/cmd/cleanup.rb:52:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

The issue vanished after I deleted azure-nuke by forcefully removing directories and untapping `ekristen/tap`.

**Comment by ekristen** [comment]
Thanks for the notice. I fixed a separate issue, I',m not sure if this would have fixed it for you, but everything is working for me.

Please run the following. 

```
brew uninstall azure-nuke@1
brew update
brew install azure-nuke@1
```

**Comment by Chan9390** [comment]
Nope, I did `brew install ekristen/tap/azure-nuke@1` and got the same error. Again had to force uninstall it.

**Comment by ekristen** [comment]
What OS are you on and what architecture?

**Comment by ekristen** [comment]
If you are on ARM64, I just got arm builds working again and uploaded on beta.13. Let me know if things work now.
